### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by phated** [generate/common-questions#2]
Just ran into this deep inside `generate-project`.  It is crashing because `get-value` is not installed by the dependencies (but doesn't crash in your travis tests because it isn't being used?).

I'm not sure the startup time is important enough to have problems like this creep in.  Thoughts?

**Comment by jonschlinkert** [comment]
> Just ran into this deep inside generate-project. It is crashing because get-value is not installed by the dependencies

Can you paste in the error message? That just sounds like a node error to me.

> I'm not sure the startup time is important enough to have problems like this creep in. Thoughts?

If you did indeed discover a bug, this will be the first one. 

edit: also fwiw recently we mostly use lazy-cache for CLI apps, like generate, that typically won't be browserified or webpacked. browserifying generate would be like using it on yeoman. 

Initially, we started using lazy-cache specifically in our scaffolding/build toolchain because of extremely bloated libraries that were causing our CLI apps to be slow. In the first app we used lazy-cache in, load time dropped from 1 second, to less than 100 ms. Yes, IMO that's way more than enough to justify lazy loading. Consider it this way, ever single user gets penalized every time they use any of our applications if we remove lazy-cache, only people with edge cases _might_ benefit, but only until they realize that it's a webpack bug causing the issue, and that a fix exists for it. 

(edited the grammar in the last paragraph)

**Comment by phated** [comment]
The module isn't in your dependencies but attempts to be loaded by lazy-cache. Sorry for the confusion.

**Comment by jonschlinkert** [comment]
> The module isn't in your dependencies

If lazy-cache is preventing that from bubbling that's definitely a bug, it might be an old version of lazy-cache. Do you know which module it was? (also fwiw we haven't been using lazy-cache as much. it helps that some of the most bloated modules we used are no longer in our toolchain, like inquirer. and if you're using something that lazy-cache is causing a problem in, of course we'll remove it).

**Comment by phated** [comment]
It bubbles from lazy-cache when I try to use `generate` but it isn't being caught by your travis-ci in this project (likely because that code path isn't being tested) but the missing dep would have been caught if not obscured by lazy-cache.  Hope this helps describe the issue better.

Great to hear about lazy-cache being used less!

**Comment by jonschlinkert** [comment]
well, damn. It sucks that you're experiencing an issue using generate. we love that project, I hope we can get it working smoothly for you like it does for us. 

> but the missing dep would have been caught if not obscured by lazy-cache

I just want to figure out what module it's missing from

**Comment by phated** [comment]
I tracked it back to this module.  See https://github.com/generate/common-questions/blob/master/lib/utils.js#L22 but it doesn't exist in `package.json`.

**Comment by doowb** [comment]
I added the missing dependencies. Thanks for tracking it down to this lib. They weren't getting caught in unit tests because some other dependency was installing them and they were flattened in newer versions of npm.
